export const EDU_LOGIN = 'EDU_LOGIN'
export const EDU_LOGIN_FOR_TOKEN  = 'EDU_LOGIN_FOR_TOKEN'

export const EDU_SCHOOL_START_DATE = 'EDU_SCHOOL_START_DATE'

export const EDU_SCORE = 'EDU_SCORE'
export const EDU_SCHEDULE = 'EDU_SCHEDULE'

export const EDU_RECOMMEND_GRADE = 'EDU_RECOMMEND_GRADE'
export const EDU_RECOMMEND_COLLEGE = 'EDU_RECOMMEND_COLLEGE'
export const EDU_RECOMMEND_MAJOR = 'EDU_RECOMMEND_MAJOR'
export const EDU_RECOMMEND_CLASS = 'EDU_RECOMMEND_CLASS'
export const EDU_RECOMMEND_SCHEDULE = 'EDU_RECOMMEND_SCHEDULE'

export const EDU_SET_MY_SCHEDULE  = 'EDU_SET_MY_SCHEDULE'

export const EDU_SET_CUSTOM_SCHEDULE  = 'EDU_SET_CUSTOM_SCHEDULE'

export const EDU_SET_CURR_WEEK = 'EDU_SET_CURR_WEEK'

export const EDU_SET_RECOMMEND_SCHEDULE = 'EDU_SET_RECOMMEND_SCHEDULE'

export const EDU_SET_RECOMMEND_SCHEDULE_LIST  = 'EDU_SET_RECOMMEND_SCHEDULE_LIST'

export const EDU_SET_EDITING_COURSE = 'EDU_SET_EDITING_COURSE'

export const EDU_SET_ACCOUNT = 'EDU_SET_ACCOUNT'