export const LIBRARY_BOOK_SEARCH = 'LIBRARY_BOOK_SEARCH'
export const LIBRARY_BOOK_DETAIL = 'LIBRARY_BOOK_DETAIL'
export const LIBRARY_BOOK_INFO = 'LIBRARY_BOOK_INFO'

export const LIBRARY_READER_STATE = 'LIBRARY_READER_STATE'
export const LIBRARY_READER_LOGIN = 'LIBRARY_READER_LOGIN'
export const LIBRARY_READER_CAPTCHA = 'LIBRARY_READER_CAPTCHA'
export const LIBRARY_READER_INFO = 'LIBRARY_READER_INFO'
export const LIBRARY_READER_CURRENT_CHECKOUT = 'LIBRARY_READER_CURRENT_CHECKOUT'
export const LIBRARY_READER_HISTROY_CHECKOUT = 'LIBRARY_READER_HISTROY_CHECKOUT'

export const LIBRARY_LIKE_BOOK = 'LIBRARY_LIKE_BOOK'
export const LIBRARY_DISLIKE_BOOK = 'LIBRARY_DISLIKE_BOOK'